name: sih_testing1
description: A simple finance app UI

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
<<<<<<< HEAD
  http: ^1.2.2
  
  
=======
  http: ^0.13.3

>>>>>>> d55e2b7c3e17076f517d175048a5396dd0d79323
  # Add any additional packages here

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
